//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoFirstWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emp
    {
        public int empno { get; set; }
        public string ename { get; set; }
        public Nullable<int> jcode { get; set; }
        public Nullable<int> mgrno { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<double> commission { get; set; }
        public Nullable<int> DEPTNO { get; set; }
    }
}
