//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoFirstWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudentDetail()
        {
            this.tblStudentDetScores = new HashSet<tblStudentDetScore>();
        }
    
        public string studID { get; set; }
        public string studname { get; set; }
        public Nullable<int> studAge { get; set; }
        public string studMobile { get; set; }
        public string studGender { get; set; }
        public Nullable<int> studStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentDetScore> tblStudentDetScores { get; set; }
    }
}
